# Generated by Django 5.2.8 on 2025-11-24 05:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoElectoral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del Proceso')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Elección')),
                ('anio', models.CharField(max_length=4, verbose_name='Año')),
                ('etapa_actual', models.CharField(choices=[('convocatoria', 'Convocatoria'), ('inscripcion', 'Inscripción de Listas'), ('subsanacion', 'Subsanación'), ('tachas', 'Periodo de Tachas'), ('publicacion', 'Publicación de Listas Hábiles'), ('campania', 'Campaña Electoral'), ('votacion', 'Jornada Electoral'), ('escrutinio', 'Escrutinio'), ('proclamacion', 'Proclamación de Resultados'), ('impugnaciones', 'Impugnaciones'), ('credenciales', 'Entrega de Credenciales')], default='convocatoria', max_length=50, verbose_name='Etapa Actual')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Proceso Activo')),
            ],
            options={
                'verbose_name': 'Proceso Electoral',
                'verbose_name_plural': 'Procesos Electorales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('es_postulante', models.BooleanField(default=False, verbose_name='¿Es Postulante?')),
                ('es_admin', models.BooleanField(default=False, verbose_name='¿Es Administrador?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ListaElectoral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Lista')),
                ('tipo', models.CharField(choices=[('Rectorado', 'Rectorado'), ('Decanato', 'Decanato'), ('Asamblea', 'Asamblea'), ('Consejo', 'Consejo')], max_length=50, verbose_name='Tipo de Elección')),
                ('anio', models.CharField(max_length=4, verbose_name='Año Electoral')),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtítulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('facultad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facultad')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True, verbose_name='Lista Activa')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Lista Electoral',
                'verbose_name_plural': 'Listas Electorales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('anio', models.CharField(max_length=4, verbose_name='Año')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_integrantes/', verbose_name='Foto')),
                ('cv_url', models.URLField(blank=True, null=True, verbose_name='URL de CV')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('lista_electoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='api.listaelectoral', verbose_name='Lista Electoral')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300, verbose_name='Título del Documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('plan_trabajo', 'Plan de Trabajo'), ('plan_gobierno', 'Plan de Gobierno'), ('propuesta_academica', 'Propuesta Académica'), ('hoja_vida', 'Hoja de Vida'), ('declaracion_jurada', 'Declaración Jurada'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Archivo')),
                ('url_simulada', models.URLField(blank=True, null=True, verbose_name='URL Simulada')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tamaño_archivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamaño del Archivo')),
                ('lista_electoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.listaelectoral', verbose_name='Lista Electoral')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='listaelectoral',
            index=models.Index(fields=['tipo', 'anio'], name='api_listael_tipo_20b528_idx'),
        ),
        migrations.AddIndex(
            model_name='listaelectoral',
            index=models.Index(fields=['nombre'], name='api_listael_nombre_fbc4f0_idx'),
        ),
    ]
